#!/bin/bash

# Get list of IP ranges
#
# First we use curl to grab the official list of ranges from Amazon. The -s
# prevents extraneous output from curl, and the -L makes it follow redirects.
#
# The ranges are passed to jq, a JSON parser. The -r makes jq output raw data
# without quotes. We only need the list of prefixes, so we discard everything
# else.
RANGES=$(curl -s -L https://ip-ranges.amazonaws.com/ip-ranges.json \
    | jq -r '.prefixes[].ip_prefix' \
    | sort -Vu)

echo "$RANGES" > /etc/symbiosis/firewall/incoming.d/01-reject
